# Template for deployment of spawner image to ACR
jobs:
- deployment:
  displayName: 'Build docker spawner image'
  environment: $(DEPLOY_ENVIRONMENT)
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(IMAGE_REPOSITORY)
              dockerfile: $(DOCKER_FILEPATH)
              containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION)
              tags: |
                $(build.buildid)
                $(TAG)