trigger:
- none

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'worker'
  containerRegistry: 'microcontainerapp$(DEPLOY_ENVIRONMENT).azurecr.io'
  dockerfilePath: '**/worker.Dockerfile'
  tag: 'latest'

pool:
  name: local_pool
  demands:
    - agent.os -equals Darwin

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
    - template: pipeline-templates/build-and-push-image.yml
