trigger:
- none

variables:
  IMAGE_REPOSITORY: 'worker'
  CONTAINER_REGISTRY: 'microcontainerappprod.azurecr.io'
  DOCKER_FILEPATH: '$(Build.SourcesDirectory)/Dockerfile'
  TAG: 'latest'
  DOCKER_REGISTRY_SERVICE_CONNECTION: 'microappdockerprod'
  FUNCTIONAPPNAME: 'spawnerprod'
  WORKING_DIRECTORY: '$(System.DefaultWorkingDirectory)/spawner'


pool:
  vmImage: ubuntu-latest

stages:
- template: pipeline-templates/zip-and-deploy-function.yml
- stage: BuildSpawnerImage
  displayName: Build and push spawner image
  jobs:
    - template: pipeline-templates/build-and-push-image.yml
