trigger:
- master

variables:
  DOCKER_REGISTRY_SERVICE_CONNECTION: 'microappdockertest'
  IMAGE_REPOSITORY: 'worker'
  CONTAINER_REGISTRY: 'microcontainerapptest.azurecr.io'
  DOCKER_FILEPATH: '$(Build.SourcesDirectory)/Dockerfile'
  TAG: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildSpawnerImage
  displayName: Build and push spawner image
  jobs:
    - template: pipeline-templates/build-and-push-image.yml