trigger:
- master

variables:
  IMAGE_REPOSITORY: 'worker'
  CONTAINER_REGISTRY: 'microcontainerapp$(DEPLOY_ENVIRONMENT).azurecr.io'
  TAG: 'latest'
  DOCKER_FILEPATH: '$(Build.SourcesDirectory)/Dockerfile'
  DOCKER_REGISTRY_SERVICE_CONNECTION: 'microapp_test_acr'

pool:
  name: local_pool
  demands:
    - agent.os -equals Darwin

stages:
- stage: Build
  displayName: Build and push spawner container
  jobs:
    - template: pipeline-templates/build-and-push-image.yml
