trigger:
- master

variables:
  IMAGE_REPOSITORY: 'worker'
  CONTAINER_REGISTRY: 'microcontainerapp$(DEPLOY_ENVIRONMENT).azurecr.io'
  TAG: 'latest'
  DOCKER_REGISTRY_SERVICE_CONNECTION: 'microapp_test_acr'

pool:
  name: local_pool
  demands:
    - agent.os -equals Darwin

stages:
- stage: Build
  displayName: Build and push spawner container
  jobs:
    - deployment:
      displayName: 'Build docker image'
      environment: $(DEPLOY_ENVIRONMENT)
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Docker@2
                displayName: Build and push an image to container registry
                inputs:
                  command: buildAndPush
                  repository: $(IMAGE_REPOSITORY)
                  buildContext: '$(Build.Repository.LocalPath)'
                  dockerfile: '**/worker.Dockerfile'
                  CONTAINER_REGISTRY: $(DOCKER_REGISTRY_SERVICE_CONNECTION)
                  tags: |
                    $(build.buildid)
                    $(TAG)
